// Generated by npm run db:types fallback command. Do not edit manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      admin: {
        Row: {
          created_at: string | null
          email: string
          id: string
          name: string
          role: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          email: string
          id: string
          name: string
          role?: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          email?: string
          id?: string
          name?: string
          role?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      announcement: {
        Row: {
          content: string
          created_at: string | null
          crisis_id: string | null
          id: string
          office_id: string | null
          priority: string | null
          title: string
          updated_at: string | null
        }
        Insert: {
          content: string
          created_at?: string | null
          crisis_id?: string | null
          id?: string
          office_id?: string | null
          priority?: string | null
          title: string
          updated_at?: string | null
        }
        Update: {
          content?: string
          created_at?: string | null
          crisis_id?: string | null
          id?: string
          office_id?: string | null
          priority?: string | null
          title?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "announcement_crisis_id_fkey"
            columns: ["crisis_id"]
            isOneToOne: false
            referencedRelation: "crisis"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "announcement_office_id_fkey"
            columns: ["office_id"]
            isOneToOne: false
            referencedRelation: "office"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_log: {
        Row: {
          action: string
          actor_id: string
          actor_name: string | null
          actor_role: string
          created_at: string
          entity_id: string | null
          entity_type: string
          id: string
          metadata: Json | null
        }
        Insert: {
          action: string
          actor_id: string
          actor_name?: string | null
          actor_role: string
          created_at?: string
          entity_id?: string | null
          entity_type: string
          id?: string
          metadata?: Json | null
        }
        Update: {
          action?: string
          actor_id?: string
          actor_name?: string | null
          actor_role?: string
          created_at?: string
          entity_id?: string | null
          entity_type?: string
          id?: string
          metadata?: Json | null
        }
        Relationships: []
      }
      crisis: {
        Row: {
          affected_areas: string[] | null
          created_at: string | null
          features: Json | null
          id: string
          name: string | null
          office_id: string | null
          required_actions: string | null
          resolution_notes: string | null
          severity: string | null
          status: string | null
          summary: string | null
          type: string
          updated_at: string | null
        }
        Insert: {
          affected_areas?: string[] | null
          created_at?: string | null
          features?: Json | null
          id?: string
          name?: string | null
          office_id?: string | null
          required_actions?: string | null
          resolution_notes?: string | null
          severity?: string | null
          status?: string | null
          summary?: string | null
          type: string
          updated_at?: string | null
        }
        Update: {
          affected_areas?: string[] | null
          created_at?: string | null
          features?: Json | null
          id?: string
          name?: string | null
          office_id?: string | null
          required_actions?: string | null
          resolution_notes?: string | null
          severity?: string | null
          status?: string | null
          summary?: string | null
          type?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "crisis_office_id_fkey"
            columns: ["office_id"]
            isOneToOne: false
            referencedRelation: "office"
            referencedColumns: ["id"]
          },
        ]
      }
      emergency_contact: {
        Row: {
          created_at: string | null
          icon: string | null
          id: string
          label: string
          note: string | null
          number: string
          office_id: string
        }
        Insert: {
          created_at?: string | null
          icon?: string | null
          id?: string
          label: string
          note?: string | null
          number: string
          office_id: string
        }
        Update: {
          created_at?: string | null
          icon?: string | null
          id?: string
          label?: string
          note?: string | null
          number?: string
          office_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "emergency_contact_office_id_fkey"
            columns: ["office_id"]
            isOneToOne: false
            referencedRelation: "office"
            referencedColumns: ["id"]
          },
        ]
      }
      help_request: {
        Row: {
          created_at: string | null
          crisis_id: string | null
          id: string
          location: string | null
          notes: string | null
          office_id: string | null
          stakeholder_id: string | null
          status: string | null
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          crisis_id?: string | null
          id?: string
          location?: string | null
          notes?: string | null
          office_id?: string | null
          stakeholder_id?: string | null
          status?: string | null
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          crisis_id?: string | null
          id?: string
          location?: string | null
          notes?: string | null
          office_id?: string | null
          stakeholder_id?: string | null
          status?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "help_request_crisis_id_fkey"
            columns: ["crisis_id"]
            isOneToOne: false
            referencedRelation: "crisis"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "help_request_office_id_fkey"
            columns: ["office_id"]
            isOneToOne: false
            referencedRelation: "office"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "help_request_stakeholder_id_fkey"
            columns: ["stakeholder_id"]
            isOneToOne: false
            referencedRelation: "stakeholder"
            referencedColumns: ["id"]
          },
        ]
      }
      message: {
        Row: {
          content: string
          created_at: string | null
          help_request_id: string
          id: string
          sender_id: string
          sender_name: string | null
          sender_role: string
        }
        Insert: {
          content: string
          created_at?: string | null
          help_request_id: string
          id?: string
          sender_id: string
          sender_name?: string | null
          sender_role: string
        }
        Update: {
          content?: string
          created_at?: string | null
          help_request_id?: string
          id?: string
          sender_id?: string
          sender_name?: string | null
          sender_role?: string
        }
        Relationships: [
          {
            foreignKeyName: "message_help_request_id_fkey"
            columns: ["help_request_id"]
            isOneToOne: false
            referencedRelation: "help_request"
            referencedColumns: ["id"]
          },
        ]
      }
      office: {
        Row: {
          age: number | null
          contact: string | null
          created_at: string | null
          email: string
          gender: string | null
          id: string
          is_admin: boolean | null
          name: string
          office_name: string | null
          role: string
          updated_at: string | null
        }
        Insert: {
          age?: number | null
          contact?: string | null
          created_at?: string | null
          email: string
          gender?: string | null
          id?: string
          is_admin?: boolean | null
          name: string
          office_name?: string | null
          role: string
          updated_at?: string | null
        }
        Update: {
          age?: number | null
          contact?: string | null
          created_at?: string | null
          email?: string
          gender?: string | null
          id?: string
          is_admin?: boolean | null
          name?: string
          office_name?: string | null
          role?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      progress_report: {
        Row: {
          content: string
          created_at: string | null
          crisis_id: string | null
          icon: string | null
          id: string
          office_id: string | null
          title: string | null
          update_type: string | null
        }
        Insert: {
          content: string
          created_at?: string | null
          crisis_id?: string | null
          icon?: string | null
          id?: string
          office_id?: string | null
          title?: string | null
          update_type?: string | null
        }
        Update: {
          content?: string
          created_at?: string | null
          crisis_id?: string | null
          icon?: string | null
          id?: string
          office_id?: string | null
          title?: string | null
          update_type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "progress_report_crisis_id_fkey"
            columns: ["crisis_id"]
            isOneToOne: false
            referencedRelation: "crisis"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "progress_report_office_id_fkey"
            columns: ["office_id"]
            isOneToOne: false
            referencedRelation: "office"
            referencedColumns: ["id"]
          },
        ]
      }
      stakeholder: {
        Row: {
          age: number | null
          community: string | null
          contact: string | null
          created_at: string | null
          current_address: string | null
          email: string
          id: string
          name: string
          permanent_address: string | null
          role: string
          updated_at: string | null
        }
        Insert: {
          age?: number | null
          community?: string | null
          contact?: string | null
          created_at?: string | null
          current_address?: string | null
          email: string
          id?: string
          name: string
          permanent_address?: string | null
          role: string
          updated_at?: string | null
        }
        Update: {
          age?: number | null
          community?: string | null
          contact?: string | null
          created_at?: string | null
          current_address?: string | null
          email?: string
          id?: string
          name?: string
          permanent_address?: string | null
          role?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      survey: {
        Row: {
          created_at: string | null
          crisis_id: string | null
          id: string
          office_id: string | null
          questions: Json | null
          status: string | null
          survey_type: string | null
          title: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          crisis_id?: string | null
          id?: string
          office_id?: string | null
          questions?: Json | null
          status?: string | null
          survey_type?: string | null
          title: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          crisis_id?: string | null
          id?: string
          office_id?: string | null
          questions?: Json | null
          status?: string | null
          survey_type?: string | null
          title?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "survey_crisis_id_fkey"
            columns: ["crisis_id"]
            isOneToOne: false
            referencedRelation: "crisis"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "survey_office_id_fkey"
            columns: ["office_id"]
            isOneToOne: false
            referencedRelation: "office"
            referencedColumns: ["id"]
          },
        ]
      }
      survey_response: {
        Row: {
          answers: Json | null
          created_at: string | null
          id: string
          stakeholder_id: string | null
          survey_id: string | null
        }
        Insert: {
          answers?: Json | null
          created_at?: string | null
          id?: string
          stakeholder_id?: string | null
          survey_id?: string | null
        }
        Update: {
          answers?: Json | null
          created_at?: string | null
          id?: string
          stakeholder_id?: string | null
          survey_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "survey_response_stakeholder_id_fkey"
            columns: ["stakeholder_id"]
            isOneToOne: false
            referencedRelation: "stakeholder"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "survey_response_survey_id_fkey"
            columns: ["survey_id"]
            isOneToOne: false
            referencedRelation: "survey"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
